
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 06 01:56:24 CST 2024
//----------------------------------------------------

package com.luisbaquiax.emuladordb.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 8;
  public static final int PUNTO = 22;
  public static final int SIG_MAYOR_QUE = 19;
  public static final int INSERTAR = 3;
  public static final int CADENA = 10;
  public static final int OR = 9;
  public static final int DECIMAL = 14;
  public static final int ELIMINAR = 4;
  public static final int SIG_MENOR_QUE = 18;
  public static final int SIG_DIFERENTE = 20;
  public static final int ID = 11;
  public static final int SIG_MAYOR = 17;
  public static final int FILTRAR = 6;
  public static final int COMA = 23;
  public static final int ACTUALIZAR = 5;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PUNTO_COMA = 21;
  public static final int ARCHIVO = 12;
  public static final int EN = 7;
  public static final int ENTERO = 13;
  public static final int SIG_MENOR = 16;
  public static final int SELECCIONAR = 2;
  public static final int SIG_IGUAL = 15;
}

