// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Desktop/Lenguajes y compiladores/emulador-lab-COMPI1-2024/EmuladorDB/src/main/resources/flexcup/Instrucciones.jflex


/* codigo de usuario */
package com.luisbaquiax.emuladordb.lexer;
import com.luisbaquiax.emuladordb.parser.sym;
import java.util.ArrayList;

import java_cup.runtime.*;


@SuppressWarnings("fallthrough")
public class InstrucionesLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  0,  1,  3,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  0,  4,  5,  0,  0,  0,  0,  6,  7,  5,  5,  8,  5,  9,  0, 
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  0, 11, 12, 13, 14,  0, 
     5, 15, 16, 17, 18, 19, 20, 21, 16, 22, 16, 16, 23, 24, 25, 26, 
    16, 16, 27, 28, 29, 30, 31, 16, 16, 16, 32,  0,  0,  0,  0,  5, 
     0, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 
    16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\10\15\1\0"+
    "\1\16\1\0\1\17\1\20\1\21\4\15\1\22\2\15"+
    "\1\23\2\15\1\24\1\15\1\25\34\15\1\26\1\15"+
    "\1\27\2\15\1\30\1\15\1\31\1\32\3\15\1\33"+
    "\1\15\1\34";

  private static int [] zzUnpackAction() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\41\0\41\0\102\0\143\0\204\0\41\0\41"+
    "\0\41\0\41\0\245\0\41\0\306\0\41\0\347\0\u0108"+
    "\0\u0129\0\u014a\0\u016b\0\u018c\0\u01ad\0\u01ce\0\u01ef\0\143"+
    "\0\41\0\u0210\0\41\0\41\0\41\0\u0231\0\u0252\0\u0273"+
    "\0\u0294\0\u0129\0\u02b5\0\u02d6\0\u0129\0\u02f7\0\u0318\0\u0210"+
    "\0\u0339\0\u0129\0\u035a\0\u037b\0\u039c\0\u03bd\0\u03de\0\u03ff"+
    "\0\u0420\0\u0441\0\u0462\0\u0483\0\u04a4\0\u04c5\0\u04e6\0\u0507"+
    "\0\u0528\0\u0549\0\u056a\0\u058b\0\u05ac\0\u05cd\0\u05ee\0\u060f"+
    "\0\u0630\0\u0651\0\u0672\0\u0693\0\u06b4\0\u06d5\0\u0129\0\u06f6"+
    "\0\u0129\0\u0717\0\u0738\0\u0129\0\u0759\0\u0129\0\u0129\0\u077a"+
    "\0\u079b\0\u07bc\0\u0129\0\u07dd\0\u0129";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\3\21"+
    "\1\22\1\23\1\21\1\24\3\21\1\25\1\21\1\26"+
    "\2\21\1\27\1\21\43\0\1\3\36\0\4\30\1\31"+
    "\34\30\5\0\1\6\4\0\1\6\4\0\22\6\5\0"+
    "\1\6\3\0\1\32\1\13\4\0\22\6\15\0\1\33"+
    "\1\34\37\0\1\35\30\0\1\6\4\0\1\21\4\0"+
    "\2\21\1\36\7\21\1\37\2\21\1\40\4\21\5\0"+
    "\1\6\4\0\1\21\4\0\22\21\5\0\1\6\4\0"+
    "\1\21\4\0\10\21\1\41\1\21\1\42\7\21\5\0"+
    "\1\6\4\0\1\21\4\0\7\21\1\43\12\21\5\0"+
    "\1\6\4\0\1\21\4\0\12\21\1\44\7\21\5\0"+
    "\1\6\4\0\1\21\4\0\14\21\1\45\5\21\5\0"+
    "\1\6\4\0\1\21\4\0\4\21\1\46\15\21\5\0"+
    "\1\6\4\0\1\21\4\0\1\47\21\21\12\0\1\50"+
    "\33\0\1\6\4\0\1\21\4\0\16\21\1\51\3\21"+
    "\5\0\1\6\4\0\1\21\4\0\3\21\1\52\16\21"+
    "\5\0\1\6\4\0\1\21\4\0\7\21\1\53\12\21"+
    "\5\0\1\6\4\0\1\21\4\0\7\21\1\54\12\21"+
    "\5\0\1\6\4\0\1\21\4\0\10\21\1\55\11\21"+
    "\5\0\1\6\4\0\1\21\4\0\15\21\1\56\4\21"+
    "\5\0\1\6\4\0\1\21\4\0\10\21\1\57\11\21"+
    "\5\0\1\6\4\0\1\21\4\0\10\21\1\60\11\21"+
    "\5\0\1\6\4\0\1\21\4\0\17\21\1\61\2\21"+
    "\5\0\1\6\4\0\1\21\4\0\6\21\1\62\13\21"+
    "\5\0\1\6\4\0\1\21\4\0\11\21\1\63\10\21"+
    "\5\0\1\6\4\0\1\21\4\0\16\21\1\64\3\21"+
    "\5\0\1\6\4\0\1\21\4\0\4\21\1\65\15\21"+
    "\5\0\1\6\4\0\1\21\4\0\4\21\1\66\15\21"+
    "\5\0\1\6\4\0\1\21\4\0\13\21\1\67\6\21"+
    "\5\0\1\6\4\0\1\21\4\0\1\70\21\21\5\0"+
    "\1\6\4\0\1\21\4\0\12\21\1\71\7\21\5\0"+
    "\1\6\4\0\1\21\4\0\7\21\1\72\12\21\5\0"+
    "\1\6\4\0\1\21\4\0\14\21\1\73\5\21\5\0"+
    "\1\6\4\0\1\21\4\0\14\21\1\74\5\21\5\0"+
    "\1\6\4\0\1\21\4\0\2\21\1\75\17\21\5\0"+
    "\1\6\4\0\1\21\4\0\14\21\1\76\5\21\5\0"+
    "\1\6\4\0\1\21\4\0\10\21\1\77\11\21\5\0"+
    "\1\6\4\0\1\21\4\0\1\100\21\21\5\0\1\6"+
    "\4\0\1\21\4\0\12\21\1\101\7\21\5\0\1\6"+
    "\4\0\1\21\4\0\1\102\21\21\5\0\1\6\4\0"+
    "\1\21\4\0\16\21\1\103\3\21\5\0\1\6\4\0"+
    "\1\21\4\0\2\21\1\104\17\21\5\0\1\6\4\0"+
    "\1\21\4\0\4\21\1\105\15\21\5\0\1\6\4\0"+
    "\1\21\4\0\7\21\1\106\12\21\5\0\1\6\4\0"+
    "\1\21\4\0\14\21\1\107\5\21\5\0\1\6\4\0"+
    "\1\21\4\0\1\110\21\21\5\0\1\6\4\0\1\21"+
    "\4\0\14\21\1\111\5\21\5\0\1\6\4\0\1\21"+
    "\4\0\1\112\21\21\5\0\1\6\4\0\1\21\4\0"+
    "\7\21\1\113\12\21\5\0\1\6\4\0\1\21\4\0"+
    "\15\21\1\114\4\21\5\0\1\6\4\0\1\21\4\0"+
    "\21\21\1\115\5\0\1\6\4\0\1\21\4\0\14\21"+
    "\1\116\5\21\5\0\1\6\4\0\1\21\4\0\14\21"+
    "\1\117\5\21\5\0\1\6\4\0\1\21\4\0\13\21"+
    "\1\120\6\21\5\0\1\6\4\0\1\21\4\0\1\121"+
    "\21\21\5\0\1\6\4\0\1\21\4\0\12\21\1\122"+
    "\7\21\5\0\1\6\4\0\1\21\4\0\14\21\1\123"+
    "\5\21\5\0\1\6\4\0\1\21\4\0\1\124\21\21"+
    "\5\0\1\6\4\0\1\21\4\0\14\21\1\125\5\21";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2046];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\4\11\1\1\1\11\1\1\1\11"+
    "\11\1\1\0\1\11\1\0\3\11\70\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
public ArrayList<Symbol> tokens = new ArrayList<>();

  private Symbol symbol(int type) {
    return new Symbol(type, yyline+1, yycolumn+1);
  }

  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline+1, yycolumn+1, value);
  }

  private Symbol symbol(int type, Object value, int row, int col) {
      return new Symbol(type, row+1, col+1, value);
    }


  private void error(String message) {
    System.out.println("Error en linea line "+(yyline+1)+", columna "+(yycolumn+1)+" : "+message);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public InstrucionesLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { error("Simbolo invalido <"+ yytext()+">");
            }
          // fall through
          case 29: break;
          case 2:
            { /* ignoramos */
            }
          // fall through
          case 30: break;
          case 3:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
	                     tokens.add(new Symbol(sym.ARCHIVO, yytext()));
                         return symbol(sym.ARCHIVO, yytext());
            }
          // fall through
          case 31: break;
          case 4:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
            tokens.add(new Symbol(sym.PARENA, yytext()));
            return symbol(sym.PARENA, yytext());
            }
          // fall through
          case 32: break;
          case 5:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
            tokens.add(new Symbol(sym.PARENC, yytext()));
            return symbol(sym.PARENC, yytext());
            }
          // fall through
          case 33: break;
          case 6:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
          tokens.add(new Symbol(sym.COMA, yytext()));
                    return symbol(sym.COMA, yytext());
            }
          // fall through
          case 34: break;
          case 7:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
          tokens.add(new Symbol(sym.PUNTO, yytext()));
                    return symbol(sym.PUNTO, yytext());
            }
          // fall through
          case 35: break;
          case 8:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                         tokens.add(new Symbol(sym.ENTERO, yytext()));
                         return symbol(sym.ENTERO, yytext());
            }
          // fall through
          case 36: break;
          case 9:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
          tokens.add(new Symbol(sym.PCOMA, yytext()));
                     return symbol(sym.PCOMA, yytext());
            }
          // fall through
          case 37: break;
          case 10:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                          tokens.add(new Symbol(sym.SIG_MENOR, yytext()));
                         return symbol(sym.SIG_MENOR, yytext());
            }
          // fall through
          case 38: break;
          case 11:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
	                      tokens.add(new Symbol(sym.SIG_IGUAL, yytext()));
                         return symbol(sym.SIG_IGUAL, yytext());
            }
          // fall through
          case 39: break;
          case 12:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                          tokens.add(new Symbol(sym.SIG_MAYOR, yytext()));
                         return symbol(sym.SIG_MAYOR, yytext());
            }
          // fall through
          case 40: break;
          case 13:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                             tokens.add(new Symbol(sym.ID, yytext()));
                            return symbol(sym.ID, yytext());
            }
          // fall through
          case 41: break;
          case 14:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                         tokens.add(new Symbol(sym.CADENA, yytext()));
                         return symbol(sym.CADENA, yytext());
            }
          // fall through
          case 42: break;
          case 15:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                        tokens.add(new Symbol(sym.SIG_MENOR_QUE, yytext()));
                         return symbol(sym.SIG_MENOR_QUE, yytext());
            }
          // fall through
          case 43: break;
          case 16:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
         tokens.add(new Symbol(sym.SIG_DIFERENTE, yytext()));
                     return symbol(sym.SIG_DIFERENTE, yytext());
            }
          // fall through
          case 44: break;
          case 17:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                    tokens.add(new Symbol(sym.SIG_MAYOR_QUE, yytext()));
                     return symbol(sym.SIG_MAYOR_QUE, yytext());
            }
          // fall through
          case 45: break;
          case 18:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                        tokens.add(new Symbol(sym.EN, yytext()));
                        return symbol(sym.EN, yytext());
            }
          // fall through
          case 46: break;
          case 19:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                         tokens.add(new Symbol(sym.OR, yytext()));
                        return symbol(sym.OR, yytext());
            }
          // fall through
          case 47: break;
          case 20:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                          tokens.add(new Symbol(sym.DECIMAL, yytext()));
                         return symbol(sym.DECIMAL, yytext());
            }
          // fall through
          case 48: break;
          case 21:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                         tokens.add(new Symbol(sym.AND, yytext()));
                        return symbol(sym.AND, yytext());
            }
          // fall through
          case 49: break;
          case 22:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                        tokens.add(new Symbol(sym.ASIGNAR, yytext()));
                        return symbol(sym.ASIGNAR, yytext());
            }
          // fall through
          case 50: break;
          case 23:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                         tokens.add(new Symbol(sym.FILTRAR, yytext()));
                        return symbol(sym.FILTRAR, yytext());
            }
          // fall through
          case 51: break;
          case 24:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                        tokens.add(new Symbol(sym.VALORES, yytext()));
                        return symbol(sym.VALORES, yytext());
            }
          // fall through
          case 52: break;
          case 25:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                         tokens.add(new Symbol(sym.ELIMINAR, yytext()));
                         return symbol(sym.ELIMINAR, yytext());
            }
          // fall through
          case 53: break;
          case 26:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
	                     tokens.add(new Symbol(sym.INSERTAR, yytext()));
                         return symbol(sym.INSERTAR, yytext());
            }
          // fall through
          case 54: break;
          case 27:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                          tokens.add(new Symbol(sym.ACTUALIZAR, yytext()));
                         return symbol(sym.ACTUALIZAR, yytext());
            }
          // fall through
          case 55: break;
          case 28:
            { System.out.println("lexema:" +yytext()+  " linea: " +yyline+" columna: "+yycolumn);
                         tokens.add(new Symbol(sym.SELECCIONAR, yytext()));
                         return symbol(sym.SELECCIONAR, yytext());
            }
          // fall through
          case 56: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
